---
build_from:
  amd64: ghcr.io/hassio-addons/base/amd64:12.2.7
  armhf: ghcr.io/hassio-addons/base/armhf:12.2.7
  armv7: ghcr.io/hassio-addons/base/armv7:12.2.7
  aarch64: ghcr.io/hassio-addons/base/aarch64:12.2.7
codenotary:
  base_image: codenotary@frenck.dev
  signer: codenotary@degatano.com
